//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.13 at 12:48:26 PM CET 
//


package it.eurix.archtools.workflow.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.eurix.util.workflow.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.eurix.util.workflow.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WfStatus }
     * 
     */
    public WfStatus createWfStatus() {
        return new WfStatus();
    }

    /**
     * Create an instance of {@link WfDescriptor }
     * 
     */
    public WfDescriptor createWfDescriptor() {
        return new WfDescriptor();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows }
     * 
     */
    public WfDescriptor.Workflows createWfDescriptorWorkflows() {
        return new WfDescriptor.Workflows();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows.Workflow }
     * 
     */
    public WfDescriptor.Workflows.Workflow createWfDescriptorWorkflowsWorkflow() {
        return new WfDescriptor.Workflows.Workflow();
    }

    /**
     * Create an instance of {@link WfDescriptor.Services }
     * 
     */
    public WfDescriptor.Services createWfDescriptorServices() {
        return new WfDescriptor.Services();
    }

    /**
     * Create an instance of {@link WfStatus.TimeTable }
     * 
     */
    public WfStatus.TimeTable createWfStatusTimeTable() {
        return new WfStatus.TimeTable();
    }

    /**
     * Create an instance of {@link WfStatus.Params }
     * 
     */
    public WfStatus.Params createWfStatusParams() {
        return new WfStatus.Params();
    }

    /**
     * Create an instance of {@link WfStatus.Result }
     * 
     */
    public WfStatus.Result createWfStatusResult() {
        return new WfStatus.Result();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows.Workflow.Description }
     * 
     */
    public WfDescriptor.Workflows.Workflow.Description createWfDescriptorWorkflowsWorkflowDescription() {
        return new WfDescriptor.Workflows.Workflow.Description();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows.Workflow.SParam }
     * 
     */
    public WfDescriptor.Workflows.Workflow.SParam createWfDescriptorWorkflowsWorkflowSParam() {
        return new WfDescriptor.Workflows.Workflow.SParam();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows.Workflow.DParamString }
     * 
     */
    public WfDescriptor.Workflows.Workflow.DParamString createWfDescriptorWorkflowsWorkflowDParamString() {
        return new WfDescriptor.Workflows.Workflow.DParamString();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows.Workflow.DParamFile }
     * 
     */
    public WfDescriptor.Workflows.Workflow.DParamFile createWfDescriptorWorkflowsWorkflowDParamFile() {
        return new WfDescriptor.Workflows.Workflow.DParamFile();
    }

    /**
     * Create an instance of {@link WfDescriptor.Workflows.Workflow.Task }
     * 
     */
    public WfDescriptor.Workflows.Workflow.Task createWfDescriptorWorkflowsWorkflowTask() {
        return new WfDescriptor.Workflows.Workflow.Task();
    }

    /**
     * Create an instance of {@link WfDescriptor.Services.Service }
     * 
     */
    public WfDescriptor.Services.Service createWfDescriptorServicesService() {
        return new WfDescriptor.Services.Service();
    }

    /**
     * Create an instance of {@link WfStatus.TimeTable.TaskReport }
     * 
     */
    public WfStatus.TimeTable.TaskReport createWfStatusTimeTableTaskReport() {
        return new WfStatus.TimeTable.TaskReport();
    }

    /**
     * Create an instance of {@link WfStatus.Params.SParam }
     * 
     */
    public WfStatus.Params.SParam createWfStatusParamsSParam() {
        return new WfStatus.Params.SParam();
    }

    /**
     * Create an instance of {@link WfStatus.Params.DParamString }
     * 
     */
    public WfStatus.Params.DParamString createWfStatusParamsDParamString() {
        return new WfStatus.Params.DParamString();
    }

    /**
     * Create an instance of {@link WfStatus.Params.DParamFile }
     * 
     */
    public WfStatus.Params.DParamFile createWfStatusParamsDParamFile() {
        return new WfStatus.Params.DParamFile();
    }

}
