//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.13 at 12:48:26 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.prestoprime.eu/model/2012/tools", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.eurix.archtools.tool.jaxb;
